# Generated by Django 4.0.2 on 2022-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendrequest', '0002_alter_requestdata_swapin_alter_requestdata_swapout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='swapin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='swapout',
            field=models.CharField(max_length=255),
        ),
    ]
