# Generated by Django 4.0.2 on 2022-04-22 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0007_remove_housedata_cbarray_housedata_balcony_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendrequest', '0004_alter_requestdata_swapin_alter_requestdata_swapout'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='HouseData_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkboxpost.housedata'),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
