# Generated by Django 4.0.2 on 2022-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendrequest', '0005_requestdata_housedata_id_alter_requestdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='status',
            field=models.IntegerField(choices=[(0, 'Undecided'), (1, 'Accepted'), (2, 'Rejected')], null=True),
        ),
    ]
