# Generated by Django 4.0.2 on 2022-04-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendrequest', '0007_requestdata_fromhouse_id_requestdata_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdata',
            old_name='username',
            new_name='fromEmail',
        ),
    ]
