# Generated by Django 4.0.2 on 2022-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0003_delete_checkboxdata_housedata_cbarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedata',
            name='swapIn',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='swapOut',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
