# Generated by Django 4.0.2 on 2022-04-14 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkboxpost', '0004_housedata_swapin_housedata_swapout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
