# Generated by Django 4.0.2 on 2022-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0006_housedataimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housedata',
            name='cbarray',
        ),
        migrations.AddField(
            model_name='housedata',
            name='Balcony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='CarbonAlarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Cctv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='FireExtinguisher',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='FirstAidKit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Fridge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Hairdryer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Hanger',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='HotWater',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Iron',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Kitchen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Microwave',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Oven',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Party',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Pet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Smoke',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='SmokeAlarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Soap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Stove',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='ToiletPaper',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Towel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Tv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='WashingMachine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='WheelchairAccess',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Wifi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='Workspace',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
