# Generated by Django 4.0.2 on 2022-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0007_remove_housedata_cbarray_housedata_balcony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedata',
            name='postcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='housedata',
            name='privince',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
