# Generated by Django 4.0.2 on 2022-04-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0008_housedata_postcode_housedata_privince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housedata',
            old_name='privince',
            new_name='province',
        ),
    ]
