# Generated by Django 4.0.2 on 2022-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkboxpost', '0009_rename_privince_housedata_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseDataImage',
        ),
    ]
